import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SideBar from '../components/sidebar'
import Main from '../components/main'
import Footer from '../components/footer'
import { Grid } from '@chakra-ui/react'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Tim Blog!</a>
        </h1>
        <Grid
          templateAreas={`"header header"
                  "nav main"
                  "nav footer"`}
          gridTemplateRows={'50px 1fr 30px'}
          gridTemplateColumns={'200px 1fr'}
          h='500px'
          gap='5'
          color='blackAlpha.700'
          fontWeight='bold'
        >
        <SideBar />
        <Main />
        <Footer />

        </Grid>

        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/timbaron"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built with Love by Timothy Akiode
          
        </a>
      </footer>
    </div>
  )
}
